db.books.insert(
    [
        {
            uri: 'kca://book/amzn1.gr.book.v1.7H_nkqMOZ36BaN4MmVrK2w',
            title: 'The Twitter Book',
            title_without_series: 'The Twitter Book',
            image_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328834986l/6356381._SX98_.jpg',
            small_image_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328834986l/6356381._SX50_.jpg',
            large_image_url: '',
            link: 'https://www.goodreads.com/book/show/6356381-the-twitter-book',
            num_pages: '240',
            format: 'Paperback',
            edition_information: '',
            publisher: "O'Reilly Media",
            publication_day: '20',
            publication_year: '2009',
            publication_month: '5',
            average_rating: '3.64',
            ratings_count: '349',
            description: "'Media organizations should take note of Twitter's power to quickly reach their target consumers.' --Tim O'Reilly (@timoreilly), in a Los Angeles Times interview, March 2009<br /><br />This practical guide will teach you everything you need to know to quickly become a Twitter power user. It includes information on the latest third party applications, strategies and tactics for using Twitter's 140-character messages as a serious--and effective--way to boost your business, as well as how to turn Twitter into your personal newspaper, tracking breaking news and learning what matters to you and your friends.<br /><br />Co-written by Tim O'Reilly and Sarah Milstein, widely followed and highly respected twitterers, the practical information in <i>The Twitter Book</i> is presented in an innovative, visually rich format that's packed with clear explanations and examples of best practices that show Twitter in action, as demonstrated by the work of over 60 twitterers.<br /><br />This book will help you:<br /><br /><br />Use Twitter to connect with colleagues, customers, family, and friends Stand out on Twitter Avoid common Twitter gaffes and pitfalls Build a critical professional communications channel with Twitter--and use the best third-party tools that help you manage it. If you want to know how to use Twitter like a pro, <i>The Twitter Book</i> will quickly get you up to speed.<br /><br />About the author:<br /><br /> Tim O Reilly (@timoreilly), founder and CEO of O Reilly Media, has hundreds of thousands of followers on Twitter. Sarah Milstein (@SarahM) frequently writes, speaks and teaches about Twitter; she was the 21st user of Twitter.",
            author: "Tim O'Reilly",
            published: '2009',
            work: {
                id: '6543098',
                uri: 'kca://work/amzn1.gr.work.v1.TUp6yJI-rwwWp7bUSQ0K5g',
            },
        },
        {
            uri: 'kca://book/amzn1.gr.book.v1.zR9r5GRYWtxBrsDhgvCJJQ',
            title: 'Context',
            title_without_series: 'Context',
            image_url: 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
            small_image_url: 'https://s.gr-assets.com/assets/nophoto/book/50x75-a91bf249278a81aabab721ef782c4a74.png',
            large_image_url: '',
            link: 'https://www.goodreads.com/book/show/21562603-context',
            num_pages: '241',
            format: 'ebook',
            edition_information: '',
            publisher: 'Tachyon Publications',
            publication_day: '14',
            publication_year: '2014',
            publication_month: '5',
            average_rating: '3.69',
            ratings_count: '329',
            description: "One of the internet's most celebrated hi-tech culture mavens returns with this second collection of essays and polemics. Discussing complex topics in an accessible manner, Cory Doctorow shares visions of a future where artists control their own destinies and where freedom of expression is tempered with the view that creators need to benefit from their own creations. From extolling the Etsy marketverse to excoriating Apple for dumbing-down technology while creating an information monopoly, each unique piece is brief, witty, and at the cutting edge of tech. Now a stay-at-home dad as well as an international activist, Doctorow writes as eloquently about creating internet real-time theater with his daughter as he does in lambasting the corporations that want to limit and profit from inherent intellectual freedoms.",
            author: 'Cory Doctorow',
            published: '2014',
            work: {
                id: '17672729',
                uri: 'kca://work/amzn1.gr.work.v1.RQcuW5v2Xm_5LzGSz4X4sg',
            },
        },
        {
            uri: 'kca://book/amzn1.gr.book.v1.eNeASmA1DFyYGzBj875xXw',
            title: 'How Data Science Is Transforming Health Care',
            title_without_series: 'How Data Science Is Transforming Health Care',
            image_url: 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
            small_image_url: 'https://s.gr-assets.com/assets/nophoto/book/50x75-a91bf249278a81aabab721ef782c4a74.png',
            large_image_url: '',
            link: 'https://www.goodreads.com/book/show/18874082-how-data-science-is-transforming-health-care',
            num_pages: '',
            format: '',
            edition_information: '',
            publisher: '',
            publication_day: '',
            publication_year: '',
            publication_month: '',
            average_rating: '3.47',
            ratings_count: '108',
            description: '',
            author: 'Mike Loukides',
            published: '',
            work: {
                id: '21986712',
                uri: 'kca://work/amzn1.gr.work.v1.z6jG-sovypTaayRgqCM3qA',
            },
        },
        {
            uri: 'kca://book/amzn1.gr.book.v1.vZFLBU6YBsidiZLPsYnQsA',
            title: 'Maker of Dune',
            title_without_series: 'Maker of Dune',
            image_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1370630957l/53751._SX98_.jpg',
            small_image_url: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1370630957l/53751._SY75_.jpg',
            large_image_url: '',
            link: 'https://www.goodreads.com/book/show/53751.Maker_of_Dune',
            num_pages: '279',
            format: 'Paperback',
            edition_information: '',
            publisher: 'Berkley Trade',
            publication_day: '1',
            publication_year: '1987',
            publication_month: '5',
            average_rating: '3.99',
            ratings_count: '93',
            description: '',
            author: 'Frank Herbert',
            published: '1987',
            work: {
                id: '52420',
                uri: 'kca://work/amzn1.gr.work.v1.msmZ5NnoEaX15qtweeJ5Fw',
            },
        },
        {
            uri: 'kca://book/amzn1.gr.book.v1.ckSJQpACtH4LXJsqZeRXHQ',
            title: 'What is Web 2.0',
            title_without_series: 'What is Web 2.0',
            image_url: 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
            small_image_url: 'https://s.gr-assets.com/assets/nophoto/book/50x75-a91bf249278a81aabab721ef782c4a74.png',
            large_image_url: '',
            link: 'https://www.goodreads.com/book/show/20553190-what-is-web-2-0',
            num_pages: '',
            format: '',
            edition_information: '',
            publisher: '',
            publication_day: '',
            publication_year: '',
            publication_month: '',
            average_rating: '3.61',
            ratings_count: '36',
            description: "<p>The concept of 'Web 2.0' began with a conference brainstorming session between O'Reilly and MediaLive International. Dale Dougherty, web pioneer and O'Reilly VP, noted that far from having 'crashed', the web was more important than ever, with exciting new applications and sites popping up with surprising regularity. What's more, the companies that had survived the collapse seemed to have some things in common. Could it be that the dot-com collapse marked some kind of turning point for the web, such that a call to action such as 'Web 2.0' might make sense? We agreed that it did, and so the Web 2.0 Conference was born.<br /><br /><br />In the year and a half since, the term 'Web 2.0' has clearly taken hold, with more than 9.5 million citations in Google. But there's still a huge amount of disagreement about just what Web 2.0 means, with some people decrying it as a meaningless marketing buzzword, and others accepting it as the new conventional wisdom.<br /><br /><br />This article is an attempt to clarify just what we mean by Web 2.0.</p>",
            author: "Tim O'Reilly'",
            published: '',
            work: {
                id: '22812755',
                uri: 'kca://work/amzn1.gr.work.v1.W_Xsp7FVjsF2V8YLr-IQ6Q',
            },
        },
    ],
);
